source 'https://rubygems.org'

gem 'pg'

gem 'grape'
gem 'grape-entity'
gem 'grape_oauth2', git: 'https://github.com/nbulaj/grape_oauth2.git'

gem 'rake'
gem 'rack-cors', require: 'rack/cors'

gem 'dotenv'

gem 'bcrypt'
gem 'activerecord'
gem 'otr-activerecord'

gem 'puma'

group :test do
  gem 'rspec-rails'
  gem 'database_cleaner'
  gem 'coveralls', require: false
  gem 'rack-test', require: 'rack/test'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
